# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 15:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CounsellorStudentDBMS', '0002_auto_20171110_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
